
/*
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */


/* THIS FILE HAS BEEN AUTOGENERATED BY generate.py, DO NOT MODIFY */

#include <stdint.h>
#include "pi_ros2_interface/pi-protocol.h"
#include "pi_ros2_interface/pi-messages.h"
#include <stdio.h>

// ---- IMU ---- //
#if (PI_MODE & PI_TX) && (PI_MSG_IMU_MODE & PI_TX)
pi_IMU_t piMsgImuTx = {.id=PI_MSG_IMU_ID, .len=PI_MSG_IMU_PAYLOAD_LEN};
#endif

#if (PI_MODE & PI_RX) && (PI_MSG_IMU_MODE & PI_RX)
pi_IMU_t piMsgImuA = {.id=PI_MSG_IMU_ID, .len=PI_MSG_IMU_PAYLOAD_LEN};
pi_IMU_t piMsgImuB = {.id=PI_MSG_IMU_ID, .len=PI_MSG_IMU_PAYLOAD_LEN};
pi_IMU_t* piMsgImuRx = NULL;
pi_msg_rx_state_t piMsgImuRxState = PI_MSG_RX_STATE_NONE;
#endif


// ---- FAKE_GPS ---- //
#if (PI_MODE & PI_TX) && (PI_MSG_FAKE_GPS_MODE & PI_TX)
pi_FAKE_GPS_t piMsgFakeGpsTx = {.id=PI_MSG_FAKE_GPS_ID, .len=PI_MSG_FAKE_GPS_PAYLOAD_LEN};
#endif

#if (PI_MODE & PI_RX) && (PI_MSG_FAKE_GPS_MODE & PI_RX)
pi_FAKE_GPS_t piMsgFakeGpsA = {.id=PI_MSG_FAKE_GPS_ID, .len=PI_MSG_FAKE_GPS_PAYLOAD_LEN};
pi_FAKE_GPS_t piMsgFakeGpsB = {.id=PI_MSG_FAKE_GPS_ID, .len=PI_MSG_FAKE_GPS_PAYLOAD_LEN};
pi_FAKE_GPS_t* piMsgFakeGpsRx = NULL;
pi_msg_rx_state_t piMsgFakeGpsRxState = PI_MSG_RX_STATE_NONE;
#endif


// ---- EXTERNAL_POSE ---- //
#if (PI_MODE & PI_TX) && (PI_MSG_EXTERNAL_POSE_MODE & PI_TX)
pi_EXTERNAL_POSE_t piMsgExternalPoseTx = {.id=PI_MSG_EXTERNAL_POSE_ID, .len=PI_MSG_EXTERNAL_POSE_PAYLOAD_LEN};
#endif

#if (PI_MODE & PI_RX) && (PI_MSG_EXTERNAL_POSE_MODE & PI_RX)
pi_EXTERNAL_POSE_t piMsgExternalPoseA = {.id=PI_MSG_EXTERNAL_POSE_ID, .len=PI_MSG_EXTERNAL_POSE_PAYLOAD_LEN};
pi_EXTERNAL_POSE_t piMsgExternalPoseB = {.id=PI_MSG_EXTERNAL_POSE_ID, .len=PI_MSG_EXTERNAL_POSE_PAYLOAD_LEN};
pi_EXTERNAL_POSE_t* piMsgExternalPoseRx = NULL;
pi_msg_rx_state_t piMsgExternalPoseRxState = PI_MSG_RX_STATE_NONE;
#endif


// ---- POS_SETPOINT ---- //
#if (PI_MODE & PI_TX) && (PI_MSG_POS_SETPOINT_MODE & PI_TX)
pi_POS_SETPOINT_t piMsgPosSetpointTx = {.id=PI_MSG_POS_SETPOINT_ID, .len=PI_MSG_POS_SETPOINT_PAYLOAD_LEN};
#endif

#if (PI_MODE & PI_RX) && (PI_MSG_POS_SETPOINT_MODE & PI_RX)
pi_POS_SETPOINT_t piMsgPosSetpointA = {.id=PI_MSG_POS_SETPOINT_ID, .len=PI_MSG_POS_SETPOINT_PAYLOAD_LEN};
pi_POS_SETPOINT_t piMsgPosSetpointB = {.id=PI_MSG_POS_SETPOINT_ID, .len=PI_MSG_POS_SETPOINT_PAYLOAD_LEN};
pi_POS_SETPOINT_t* piMsgPosSetpointRx = NULL;
pi_msg_rx_state_t piMsgPosSetpointRxState = PI_MSG_RX_STATE_NONE;
#endif


// ---- HIL_IN ---- //
#if (PI_MODE & PI_TX) && (PI_MSG_HIL_IN_MODE & PI_TX)
pi_HIL_IN_t piMsgHilInTx = {.id=PI_MSG_HIL_IN_ID, .len=PI_MSG_HIL_IN_PAYLOAD_LEN};
#endif

#if (PI_MODE & PI_RX) && (PI_MSG_HIL_IN_MODE & PI_RX)
pi_HIL_IN_t piMsgHilInA = {.id=PI_MSG_HIL_IN_ID, .len=PI_MSG_HIL_IN_PAYLOAD_LEN};
pi_HIL_IN_t piMsgHilInB = {.id=PI_MSG_HIL_IN_ID, .len=PI_MSG_HIL_IN_PAYLOAD_LEN};
pi_HIL_IN_t* piMsgHilInRx = NULL;
pi_msg_rx_state_t piMsgHilInRxState = PI_MSG_RX_STATE_NONE;
#endif


// ---- HIL_OUT ---- //
#if (PI_MODE & PI_TX) && (PI_MSG_HIL_OUT_MODE & PI_TX)
pi_HIL_OUT_t piMsgHilOutTx = {.id=PI_MSG_HIL_OUT_ID, .len=PI_MSG_HIL_OUT_PAYLOAD_LEN};
#endif

#if (PI_MODE & PI_RX) && (PI_MSG_HIL_OUT_MODE & PI_RX)
pi_HIL_OUT_t piMsgHilOutA = {.id=PI_MSG_HIL_OUT_ID, .len=PI_MSG_HIL_OUT_PAYLOAD_LEN};
pi_HIL_OUT_t piMsgHilOutB = {.id=PI_MSG_HIL_OUT_ID, .len=PI_MSG_HIL_OUT_PAYLOAD_LEN};
pi_HIL_OUT_t* piMsgHilOutRx = NULL;
pi_msg_rx_state_t piMsgHilOutRxState = PI_MSG_RX_STATE_NONE;
#endif


// ---- VIO_POSE ---- //
#if (PI_MODE & PI_TX) && (PI_MSG_VIO_POSE_MODE & PI_TX)
pi_VIO_POSE_t piMsgVioPoseTx = {.id=PI_MSG_VIO_POSE_ID, .len=PI_MSG_VIO_POSE_PAYLOAD_LEN};
#endif

#if (PI_MODE & PI_RX) && (PI_MSG_VIO_POSE_MODE & PI_RX)
pi_VIO_POSE_t piMsgVioPoseA = {.id=PI_MSG_VIO_POSE_ID, .len=PI_MSG_VIO_POSE_PAYLOAD_LEN};
pi_VIO_POSE_t piMsgVioPoseB = {.id=PI_MSG_VIO_POSE_ID, .len=PI_MSG_VIO_POSE_PAYLOAD_LEN};
pi_VIO_POSE_t* piMsgVioPoseRx = NULL;
pi_msg_rx_state_t piMsgVioPoseRxState = PI_MSG_RX_STATE_NONE;
#endif


// ---- KEYBOARD ---- //
#if (PI_MODE & PI_TX) && (PI_MSG_KEYBOARD_MODE & PI_TX)
pi_KEYBOARD_t piMsgKeyboardTx = {.id=PI_MSG_KEYBOARD_ID, .len=PI_MSG_KEYBOARD_PAYLOAD_LEN};
#endif

#if (PI_MODE & PI_RX) && (PI_MSG_KEYBOARD_MODE & PI_RX)
pi_KEYBOARD_t piMsgKeyboardA = {.id=PI_MSG_KEYBOARD_ID, .len=PI_MSG_KEYBOARD_PAYLOAD_LEN};
pi_KEYBOARD_t piMsgKeyboardB = {.id=PI_MSG_KEYBOARD_ID, .len=PI_MSG_KEYBOARD_PAYLOAD_LEN};
pi_KEYBOARD_t* piMsgKeyboardRx = NULL;
pi_msg_rx_state_t piMsgKeyboardRxState = PI_MSG_RX_STATE_NONE;
#endif


// ---- EKF_INPUTS ---- //
#if (PI_MODE & PI_TX) && (PI_MSG_EKF_INPUTS_MODE & PI_TX)
pi_EKF_INPUTS_t piMsgEkfInputsTx = {.id=PI_MSG_EKF_INPUTS_ID, .len=PI_MSG_EKF_INPUTS_PAYLOAD_LEN};
#endif

#if (PI_MODE & PI_RX) && (PI_MSG_EKF_INPUTS_MODE & PI_RX)
pi_EKF_INPUTS_t piMsgEkfInputsA = {.id=PI_MSG_EKF_INPUTS_ID, .len=PI_MSG_EKF_INPUTS_PAYLOAD_LEN};
pi_EKF_INPUTS_t piMsgEkfInputsB = {.id=PI_MSG_EKF_INPUTS_ID, .len=PI_MSG_EKF_INPUTS_PAYLOAD_LEN};
pi_EKF_INPUTS_t* piMsgEkfInputsRx = NULL;
pi_msg_rx_state_t piMsgEkfInputsRxState = PI_MSG_RX_STATE_NONE;
#endif


// ---- OFFBOARD_POSE ---- //
#if (PI_MODE & PI_TX) && (PI_MSG_OFFBOARD_POSE_MODE & PI_TX)
pi_OFFBOARD_POSE_t piMsgOffboardPoseTx = {.id=PI_MSG_OFFBOARD_POSE_ID, .len=PI_MSG_OFFBOARD_POSE_PAYLOAD_LEN};
#endif

#if (PI_MODE & PI_RX) && (PI_MSG_OFFBOARD_POSE_MODE & PI_RX)
pi_OFFBOARD_POSE_t piMsgOffboardPoseA = {.id=PI_MSG_OFFBOARD_POSE_ID, .len=PI_MSG_OFFBOARD_POSE_PAYLOAD_LEN};
pi_OFFBOARD_POSE_t piMsgOffboardPoseB = {.id=PI_MSG_OFFBOARD_POSE_ID, .len=PI_MSG_OFFBOARD_POSE_PAYLOAD_LEN};
pi_OFFBOARD_POSE_t* piMsgOffboardPoseRx = NULL;
pi_msg_rx_state_t piMsgOffboardPoseRxState = PI_MSG_RX_STATE_NONE;
#endif


// ---- OFFBOARD_POSE_COV ---- //
#if (PI_MODE & PI_TX) && (PI_MSG_OFFBOARD_POSE_COV_MODE & PI_TX)
pi_OFFBOARD_POSE_COV_t piMsgOffboardPoseCovTx = {.id=PI_MSG_OFFBOARD_POSE_COV_ID, .len=PI_MSG_OFFBOARD_POSE_COV_PAYLOAD_LEN};
#endif

#if (PI_MODE & PI_RX) && (PI_MSG_OFFBOARD_POSE_COV_MODE & PI_RX)
pi_OFFBOARD_POSE_COV_t piMsgOffboardPoseCovA = {.id=PI_MSG_OFFBOARD_POSE_COV_ID, .len=PI_MSG_OFFBOARD_POSE_COV_PAYLOAD_LEN};
pi_OFFBOARD_POSE_COV_t piMsgOffboardPoseCovB = {.id=PI_MSG_OFFBOARD_POSE_COV_ID, .len=PI_MSG_OFFBOARD_POSE_COV_PAYLOAD_LEN};
pi_OFFBOARD_POSE_COV_t* piMsgOffboardPoseCovRx = NULL;
pi_msg_rx_state_t piMsgOffboardPoseCovRxState = PI_MSG_RX_STATE_NONE;
#endif


// ---- DUMMY_MESSAGE ---- //
#if (PI_MODE & PI_TX) && (PI_MSG_DUMMY_MESSAGE_MODE & PI_TX)
pi_DUMMY_MESSAGE_t piMsgDummyMessageTx = {.id=PI_MSG_DUMMY_MESSAGE_ID, .len=PI_MSG_DUMMY_MESSAGE_PAYLOAD_LEN};
#endif

#if (PI_MODE & PI_RX) && (PI_MSG_DUMMY_MESSAGE_MODE & PI_RX)
pi_DUMMY_MESSAGE_t piMsgDummyMessageA = {.id=PI_MSG_DUMMY_MESSAGE_ID, .len=PI_MSG_DUMMY_MESSAGE_PAYLOAD_LEN};
pi_DUMMY_MESSAGE_t piMsgDummyMessageB = {.id=PI_MSG_DUMMY_MESSAGE_ID, .len=PI_MSG_DUMMY_MESSAGE_PAYLOAD_LEN};
pi_DUMMY_MESSAGE_t* piMsgDummyMessageRx = NULL;
pi_msg_rx_state_t piMsgDummyMessageRxState = PI_MSG_RX_STATE_NONE;
#endif


// ---- EAGLE_STATES ---- //
#if (PI_MODE & PI_TX) && (PI_MSG_EAGLE_STATES_MODE & PI_TX)
pi_EAGLE_STATES_t piMsgEagleStatesTx = {.id=PI_MSG_EAGLE_STATES_ID, .len=PI_MSG_EAGLE_STATES_PAYLOAD_LEN};
#endif

#if (PI_MODE & PI_RX) && (PI_MSG_EAGLE_STATES_MODE & PI_RX)
pi_EAGLE_STATES_t piMsgEagleStatesA = {.id=PI_MSG_EAGLE_STATES_ID, .len=PI_MSG_EAGLE_STATES_PAYLOAD_LEN};
pi_EAGLE_STATES_t piMsgEagleStatesB = {.id=PI_MSG_EAGLE_STATES_ID, .len=PI_MSG_EAGLE_STATES_PAYLOAD_LEN};
pi_EAGLE_STATES_t* piMsgEagleStatesRx = NULL;
pi_msg_rx_state_t piMsgEagleStatesRxState = PI_MSG_RX_STATE_NONE;
#endif


// ---- EAGLE_OFFBOARD_ATTITUDE ---- //
#if (PI_MODE & PI_TX) && (PI_MSG_EAGLE_OFFBOARD_ATTITUDE_MODE & PI_TX)
pi_EAGLE_OFFBOARD_ATTITUDE_t piMsgEagleOffboardAttitudeTx = {.id=PI_MSG_EAGLE_OFFBOARD_ATTITUDE_ID, .len=PI_MSG_EAGLE_OFFBOARD_ATTITUDE_PAYLOAD_LEN};
#endif

#if (PI_MODE & PI_RX) && (PI_MSG_EAGLE_OFFBOARD_ATTITUDE_MODE & PI_RX)
pi_EAGLE_OFFBOARD_ATTITUDE_t piMsgEagleOffboardAttitudeA = {.id=PI_MSG_EAGLE_OFFBOARD_ATTITUDE_ID, .len=PI_MSG_EAGLE_OFFBOARD_ATTITUDE_PAYLOAD_LEN};
pi_EAGLE_OFFBOARD_ATTITUDE_t piMsgEagleOffboardAttitudeB = {.id=PI_MSG_EAGLE_OFFBOARD_ATTITUDE_ID, .len=PI_MSG_EAGLE_OFFBOARD_ATTITUDE_PAYLOAD_LEN};
pi_EAGLE_OFFBOARD_ATTITUDE_t* piMsgEagleOffboardAttitudeRx = NULL;
pi_msg_rx_state_t piMsgEagleOffboardAttitudeRxState = PI_MSG_RX_STATE_NONE;
#endif


// ---- EAGLE_RC_ATTITUDE ---- //
#if (PI_MODE & PI_TX) && (PI_MSG_EAGLE_RC_ATTITUDE_MODE & PI_TX)
pi_EAGLE_RC_ATTITUDE_t piMsgEagleRcAttitudeTx = {.id=PI_MSG_EAGLE_RC_ATTITUDE_ID, .len=PI_MSG_EAGLE_RC_ATTITUDE_PAYLOAD_LEN};
#endif

#if (PI_MODE & PI_RX) && (PI_MSG_EAGLE_RC_ATTITUDE_MODE & PI_RX)
pi_EAGLE_RC_ATTITUDE_t piMsgEagleRcAttitudeA = {.id=PI_MSG_EAGLE_RC_ATTITUDE_ID, .len=PI_MSG_EAGLE_RC_ATTITUDE_PAYLOAD_LEN};
pi_EAGLE_RC_ATTITUDE_t piMsgEagleRcAttitudeB = {.id=PI_MSG_EAGLE_RC_ATTITUDE_ID, .len=PI_MSG_EAGLE_RC_ATTITUDE_PAYLOAD_LEN};
pi_EAGLE_RC_ATTITUDE_t* piMsgEagleRcAttitudeRx = NULL;
pi_msg_rx_state_t piMsgEagleRcAttitudeRxState = PI_MSG_RX_STATE_NONE;
#endif




// ---- parsing function ---- //
#if (PI_MODE & PI_RX)
pi_parse_msg_result_t piParseIntoMsg(pi_parse_states_t * p, const uint8_t byte) {
    //p->curMsgId = 0;
    //p->piMsgRxBuffer = NULL;
    //p->piMsgRx_ptr = NULL;
    //p->piMsgA_ptr = NULL;
    //p->piMsgB_ptr = NULL;
    //p->piMsgRxState_ptr = NULL;
    //p->piMsgLen = 0;

    pi_parse_msg_result_t res = PI_PARSE_MSG_NO_ERROR;

    if (p->msgId > PI_MSG_MAX_ID)
        return PI_PARSE_MSG_INVALID_ID;

    //if (byteCount > PI_MSG_MAX_PAYLOAD_LEN)
    //    return PI_PARSE_MSG_EXCEEDS_MAX_PAYLOAD_LEN;

    if ((p->curMsgId != p->msgId) || (p->byteCount == 0)) {
        // reset and re-assign buffers
        p->curMsgId = p->msgId;

        switch(p->msgId) {
#if (PI_MSG_IMU_MODE & PI_RX)
            case PI_MSG_IMU_ID:
                p->piMsgRx_ptr = (void *)&piMsgImuRx;
                p->piMsgA_ptr = &piMsgImuA;
                p->piMsgB_ptr = &piMsgImuB;
                p->piMsgRxState_ptr = &piMsgImuRxState;
                p->piMsgLen = PI_MSG_IMU_PAYLOAD_LEN;
                break;
#endif
#if (PI_MSG_FAKE_GPS_MODE & PI_RX)
            case PI_MSG_FAKE_GPS_ID:
                p->piMsgRx_ptr = (void *)&piMsgFakeGpsRx;
                p->piMsgA_ptr = &piMsgFakeGpsA;
                p->piMsgB_ptr = &piMsgFakeGpsB;
                p->piMsgRxState_ptr = &piMsgFakeGpsRxState;
                p->piMsgLen = PI_MSG_FAKE_GPS_PAYLOAD_LEN;
                break;
#endif
#if (PI_MSG_EXTERNAL_POSE_MODE & PI_RX)
            case PI_MSG_EXTERNAL_POSE_ID:
                p->piMsgRx_ptr = (void *)&piMsgExternalPoseRx;
                p->piMsgA_ptr = &piMsgExternalPoseA;
                p->piMsgB_ptr = &piMsgExternalPoseB;
                p->piMsgRxState_ptr = &piMsgExternalPoseRxState;
                p->piMsgLen = PI_MSG_EXTERNAL_POSE_PAYLOAD_LEN;
                break;
#endif
#if (PI_MSG_POS_SETPOINT_MODE & PI_RX)
            case PI_MSG_POS_SETPOINT_ID:
                p->piMsgRx_ptr = (void *)&piMsgPosSetpointRx;
                p->piMsgA_ptr = &piMsgPosSetpointA;
                p->piMsgB_ptr = &piMsgPosSetpointB;
                p->piMsgRxState_ptr = &piMsgPosSetpointRxState;
                p->piMsgLen = PI_MSG_POS_SETPOINT_PAYLOAD_LEN;
                break;
#endif
#if (PI_MSG_HIL_IN_MODE & PI_RX)
            case PI_MSG_HIL_IN_ID:
                p->piMsgRx_ptr = (void *)&piMsgHilInRx;
                p->piMsgA_ptr = &piMsgHilInA;
                p->piMsgB_ptr = &piMsgHilInB;
                p->piMsgRxState_ptr = &piMsgHilInRxState;
                p->piMsgLen = PI_MSG_HIL_IN_PAYLOAD_LEN;
                break;
#endif
#if (PI_MSG_HIL_OUT_MODE & PI_RX)
            case PI_MSG_HIL_OUT_ID:
                p->piMsgRx_ptr = (void *)&piMsgHilOutRx;
                p->piMsgA_ptr = &piMsgHilOutA;
                p->piMsgB_ptr = &piMsgHilOutB;
                p->piMsgRxState_ptr = &piMsgHilOutRxState;
                p->piMsgLen = PI_MSG_HIL_OUT_PAYLOAD_LEN;
                break;
#endif
#if (PI_MSG_VIO_POSE_MODE & PI_RX)
            case PI_MSG_VIO_POSE_ID:
                p->piMsgRx_ptr = (void *)&piMsgVioPoseRx;
                p->piMsgA_ptr = &piMsgVioPoseA;
                p->piMsgB_ptr = &piMsgVioPoseB;
                p->piMsgRxState_ptr = &piMsgVioPoseRxState;
                p->piMsgLen = PI_MSG_VIO_POSE_PAYLOAD_LEN;
                break;
#endif
#if (PI_MSG_KEYBOARD_MODE & PI_RX)
            case PI_MSG_KEYBOARD_ID:
                p->piMsgRx_ptr = (void *)&piMsgKeyboardRx;
                p->piMsgA_ptr = &piMsgKeyboardA;
                p->piMsgB_ptr = &piMsgKeyboardB;
                p->piMsgRxState_ptr = &piMsgKeyboardRxState;
                p->piMsgLen = PI_MSG_KEYBOARD_PAYLOAD_LEN;
                break;
#endif
#if (PI_MSG_EKF_INPUTS_MODE & PI_RX)
            case PI_MSG_EKF_INPUTS_ID:
                p->piMsgRx_ptr = (void *)&piMsgEkfInputsRx;
                p->piMsgA_ptr = &piMsgEkfInputsA;
                p->piMsgB_ptr = &piMsgEkfInputsB;
                p->piMsgRxState_ptr = &piMsgEkfInputsRxState;
                p->piMsgLen = PI_MSG_EKF_INPUTS_PAYLOAD_LEN;
                break;
#endif
#if (PI_MSG_OFFBOARD_POSE_MODE & PI_RX)
            case PI_MSG_OFFBOARD_POSE_ID:
                p->piMsgRx_ptr = (void *)&piMsgOffboardPoseRx;
                p->piMsgA_ptr = &piMsgOffboardPoseA;
                p->piMsgB_ptr = &piMsgOffboardPoseB;
                p->piMsgRxState_ptr = &piMsgOffboardPoseRxState;
                p->piMsgLen = PI_MSG_OFFBOARD_POSE_PAYLOAD_LEN;
                break;
#endif
#if (PI_MSG_OFFBOARD_POSE_COV_MODE & PI_RX)
            case PI_MSG_OFFBOARD_POSE_COV_ID:
                p->piMsgRx_ptr = (void *)&piMsgOffboardPoseCovRx;
                p->piMsgA_ptr = &piMsgOffboardPoseCovA;
                p->piMsgB_ptr = &piMsgOffboardPoseCovB;
                p->piMsgRxState_ptr = &piMsgOffboardPoseCovRxState;
                p->piMsgLen = PI_MSG_OFFBOARD_POSE_COV_PAYLOAD_LEN;
                break;
#endif
#if (PI_MSG_DUMMY_MESSAGE_MODE & PI_RX)
            case PI_MSG_DUMMY_MESSAGE_ID:
                p->piMsgRx_ptr = (void *)&piMsgDummyMessageRx;
                p->piMsgA_ptr = &piMsgDummyMessageA;
                p->piMsgB_ptr = &piMsgDummyMessageB;
                p->piMsgRxState_ptr = &piMsgDummyMessageRxState;
                p->piMsgLen = PI_MSG_DUMMY_MESSAGE_PAYLOAD_LEN;
                break;
#endif
#if (PI_MSG_EAGLE_STATES_MODE & PI_RX)
            case PI_MSG_EAGLE_STATES_ID:
                p->piMsgRx_ptr = (void *)&piMsgEagleStatesRx;
                p->piMsgA_ptr = &piMsgEagleStatesA;
                p->piMsgB_ptr = &piMsgEagleStatesB;
                p->piMsgRxState_ptr = &piMsgEagleStatesRxState;
                p->piMsgLen = PI_MSG_EAGLE_STATES_PAYLOAD_LEN;
                break;
#endif
#if (PI_MSG_EAGLE_OFFBOARD_ATTITUDE_MODE & PI_RX)
            case PI_MSG_EAGLE_OFFBOARD_ATTITUDE_ID:
                p->piMsgRx_ptr = (void *)&piMsgEagleOffboardAttitudeRx;
                p->piMsgA_ptr = &piMsgEagleOffboardAttitudeA;
                p->piMsgB_ptr = &piMsgEagleOffboardAttitudeB;
                p->piMsgRxState_ptr = &piMsgEagleOffboardAttitudeRxState;
                p->piMsgLen = PI_MSG_EAGLE_OFFBOARD_ATTITUDE_PAYLOAD_LEN;
                break;
#endif
#if (PI_MSG_EAGLE_RC_ATTITUDE_MODE & PI_RX)
            case PI_MSG_EAGLE_RC_ATTITUDE_ID:
                p->piMsgRx_ptr = (void *)&piMsgEagleRcAttitudeRx;
                p->piMsgA_ptr = &piMsgEagleRcAttitudeA;
                p->piMsgB_ptr = &piMsgEagleRcAttitudeB;
                p->piMsgRxState_ptr = &piMsgEagleRcAttitudeRxState;
                p->piMsgLen = PI_MSG_EAGLE_RC_ATTITUDE_PAYLOAD_LEN;
                break;
#endif
            default:
                return PI_PARSE_MSG_NO_SUCH_MSG;
        }
    }

    if (p->byteCount == 0) {
        p->piMsgRxBuffer = (*(p->piMsgRxState_ptr) > PI_MSG_RX_STATE_A) ? p->piMsgA_ptr : p->piMsgB_ptr;
    } else if (p->byteCount > p->piMsgLen) {
        return PI_PARSE_MSG_EXCEEDS_MSG_PAYLOAD_LEN;
    } else if (p->byteCount == p->piMsgLen) {
        // check checksum. Either it's invalid, or we have a successful message
        if (p->checksum == byte) {
            // success! let's set the rx pointer accordingly
            *(p->piMsgRxState_ptr) = (*(p->piMsgRxState_ptr) == PI_MSG_RX_STATE_A) ? PI_MSG_RX_STATE_B : PI_MSG_RX_STATE_A;
            *(p->piMsgRx_ptr) = (*(p->piMsgRxState_ptr) == PI_MSG_RX_STATE_A) ? p->piMsgA_ptr : p->piMsgB_ptr;
            return PI_PARSE_MSG_SUCCESS;
        } else {
            return PI_PARSE_MSG_INVALID_CHECKSUM;
        }
    }

    if (p->piMsgRxBuffer) {
        *((uint8_t *)p->piMsgRxBuffer + p->byteCount + PI_MSG_PAYLOAD_LEN_BYTES + PI_MSG_ID_BYTES) = byte;
        p->checksum = crc8_calc_pi(p->checksum, byte, PI_CRC8_POLYNOMIAL);
    } else {
        return PI_PARSE_MSG_NULL_BUFFER;
    }

    return res;
}
#endif  // PI_MODE & PI_RX


// printing function
#if (PI_MODE & PI_RX) && defined(PI_USE_PRINT_MSGS)
void piPrintMsgs(int (*printer)(const char* s, ...)) {
    static int i = 0;
    printer("\n+------------ piPrintMsgs invokation %d -------------+\n", i++);
#if PI_MSG_IMU_MODE & PI_RX
    piPrintMsgImu(printer);
#endif
#if PI_MSG_FAKE_GPS_MODE & PI_RX
    piPrintMsgFakeGps(printer);
#endif
#if PI_MSG_EXTERNAL_POSE_MODE & PI_RX
    piPrintMsgExternalPose(printer);
#endif
#if PI_MSG_POS_SETPOINT_MODE & PI_RX
    piPrintMsgPosSetpoint(printer);
#endif
#if PI_MSG_HIL_IN_MODE & PI_RX
    piPrintMsgHilIn(printer);
#endif
#if PI_MSG_HIL_OUT_MODE & PI_RX
    piPrintMsgHilOut(printer);
#endif
#if PI_MSG_VIO_POSE_MODE & PI_RX
    piPrintMsgVioPose(printer);
#endif
#if PI_MSG_KEYBOARD_MODE & PI_RX
    piPrintMsgKeyboard(printer);
#endif
#if PI_MSG_EKF_INPUTS_MODE & PI_RX
    piPrintMsgEkfInputs(printer);
#endif
#if PI_MSG_OFFBOARD_POSE_MODE & PI_RX
    piPrintMsgOffboardPose(printer);
#endif
#if PI_MSG_OFFBOARD_POSE_COV_MODE & PI_RX
    piPrintMsgOffboardPoseCov(printer);
#endif
#if PI_MSG_DUMMY_MESSAGE_MODE & PI_RX
    piPrintMsgDummyMessage(printer);
#endif
#if PI_MSG_EAGLE_STATES_MODE & PI_RX
    piPrintMsgEagleStates(printer);
#endif
#if PI_MSG_EAGLE_OFFBOARD_ATTITUDE_MODE & PI_RX
    piPrintMsgEagleOffboardAttitude(printer);
#endif
#if PI_MSG_EAGLE_RC_ATTITUDE_MODE & PI_RX
    piPrintMsgEagleRcAttitude(printer);
#endif
}
#endif
